import { Dimensions, StyleSheet } from 'react-native';

const { width: screenWidth } = Dimensions.get('window');
const CAROUSEL_WIDTH = Math.min(screenWidth, 500) - 32;
const CAROUSEL_HEIGHT = CAROUSEL_WIDTH * 0.545 + 5;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9F9F6',
  },
  loadingContainer: {
    flex: 1,
    backgroundColor: '#F9F9F6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 12,
    fontSize: 15,
    color: '#6C6C6C',
    fontWeight: '500',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 24,
    paddingHorizontal: 16,
    paddingBottom: 110, // extra padding so list scrolls clear of the floating tab bar
  },
  carouselContainer: {
    width: CAROUSEL_WIDTH,
    position: 'relative',
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#FFF',
    alignSelf: 'center',
    // shadow
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 4,
  },
  carouselSlide: {
    height: CAROUSEL_HEIGHT,
    position: 'relative',
  },
  carouselImage: {
    width: CAROUSEL_WIDTH,
    height: CAROUSEL_HEIGHT,
    borderRadius: 16,
  },
  carouselOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 16,
    paddingBottom: 24,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    alignItems: 'center',
  },
  carouselTag: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#FFF',
    letterSpacing: 1,
    marginBottom: 4,
    textAlign: 'center',
  },
  carouselTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFF',
    textAlign: 'center',
  },
  paginationContainer: {
    position: 'absolute',
    bottom: 12,
    right: 16,
    flexDirection: 'row',
    alignItems: 'center',
  },
  paginationDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'rgba(255, 255, 255, 0.45)',
    marginHorizontal: 3,
  },
  paginationDotActive: {
    width: 14,
    backgroundColor: '#FFF',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1C2E24',
    marginTop: 28,
    marginBottom: 16,
  },
  restaurantCard: {
    backgroundColor: 'rgb(224, 214, 188)',
    borderRadius: 24,
    padding: 12,
    marginBottom: 20,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  restaurantImageContainer: {
    position: 'relative',
    height: 190,
    width: '100%',
    borderRadius: 16,
    overflow: 'hidden',
  },
  restaurantImage: {
    height: 190,
    width: '100%',
    borderRadius: 16,
  },
  ratingBadge: {
    position: 'absolute',
    bottom: 12,
    left: 12,
    backgroundColor: '#2B783E',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
  },
  ratingText: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: 'bold',
    marginLeft: 3,
  },
  restaurantInfo: {
    paddingHorizontal: 4,
    paddingVertical: 12,
  },
  restaurantName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1E3545',
    marginBottom: 6,
  },
  emailText: {
    fontSize: 13,
    color: '#5C6B61',
    fontWeight: '500',
    marginBottom: 8,
  },
  locationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  locationText: {
    fontSize: 14,
    color: '#8A969E',
    marginLeft: 6,
  },
  mapLinkContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 22,
    marginTop: 2,
  },
  mapLinkText: {
    fontSize: 12,
    color: '#397854',
    textDecorationLine: 'underline',
    fontWeight: '500',
  },
  grayscaleOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(128, 128, 128, 0.25)',
  },
  searchBarContainer: {
    backgroundColor: 'rgb(224, 214, 188)',
    borderRadius: 28,
    height: 56,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginVertical: 18,
    justifyContent: 'space-between',
    width: '100%',
    alignSelf: 'center',
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 8,
  },
  searchPlaceholderText: {
    fontSize: 15,
    color: '#808C94',
    flex: 1,
    marginLeft: 4,
    outlineStyle: 'none',
  },
  filterPillContainer: {
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 4,
    gap: 12,
    paddingHorizontal: 6,
  },
  allButtonActive: {
    backgroundColor: '#FFFFFF',
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  allButtonText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#1E3545',
  },
  filterIconWrapper: {
    paddingHorizontal: 2,
  },
  categoriesContainer: {
    marginVertical: 6,
    width: '100%',
  },
  categoriesScroll: {
    paddingVertical: 4,
  },
  categoryCard: {
    width: 96,
    height: 96,
    borderRadius: 16,
    marginRight: 14,
    overflow: 'hidden',
    backgroundColor: '#FFF',
    position: 'relative',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 5,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  categoryCardActive: {
    borderColor: '#2B783E',
    borderRadius: 24,
    backgroundColor: '#000',
    shadowColor: '#2B783E',
    shadowOpacity: 0.2,
    elevation: 4,
  },
  categoryImage: {
    width: '100%',
    height: '100%',
    borderRadius: 14,
  },
  categoryImageActive: {
    borderRadius: 22,
  },
  categoryOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 14,
  },
  categoryOverlayActive: {
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 22,
  },
  categoryText: {
    color: '#FFF',
    fontSize: 11,
    fontWeight: 'bold',
    letterSpacing: 0.5,
    textAlign: 'center',
    paddingHorizontal: 4,
    textTransform: 'uppercase',
  },
  categoryCloseBadge: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#2B783E',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  toastContainer: {
    position: 'absolute',
    bottom: 110,
    left: 16,
    right: 16,
    zIndex: 9999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  toastContent: {
    backgroundColor: '#008000',
    borderRadius: 25,
    paddingVertical: 12,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 6,
    width: '100%',
  },
  toastIconContainer: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  toastText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  modalContent: {
    backgroundColor: '#F9F9F6',
    borderRadius: 20,
    padding: 24,
    width: '100%',
    maxWidth: 340,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalIconContainer: {
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1E3545',
    marginBottom: 10,
    textAlign: 'center',
  },
  modalSub: {
    fontSize: 14,
    color: '#5C6B61',
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 20,
  },
  primaryButton: {
    backgroundColor: '#1a1a1a',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 24,
    width: '100%',
    alignItems: 'center',
    marginBottom: 10,
  },
  primaryButtonText: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: 'bold',
  },
  secondaryButton: {
    paddingVertical: 12,
    width: '100%',
    alignItems: 'center',
  },
  secondaryButtonText: {
    color: '#606060',
    fontSize: 14,
    fontWeight: 'bold',
    textDecorationLine: 'underline',
  },
});
